### ISSUE TITLE
bug in train file

### ISSUE THREAD

**Issue by AaronJing** [hxuaj/tf2-faster-rcnn#4]
#1 Regarding this issue, my current workaround is to create a new model with `is_training=False`   and copy weights into the new model. Not sure if I did something wrong, since I am using TensorFlow r2.11.0.
```
temp_model = FasterRCNN(is_training=False)
temp_model(init_model())
temp_model.set_weights(model.get_weights())
ap ,mAP = voc_eval(eval_ds, temp_model, ds.num_classes)
```

**Comment by hxuaj** [comment]
Thx @AaronJing , you did the right thing.
After building the FasterRCNN model, it requires a "dummy forward path" to build the network variables before actually loading the weights and it's done by line 61 to line 81 in train.py.
On testing new images, please check on test.py from line 126 to 133.
